FROM vllm/vllm-openai:v0.16.0-cu130

ENV PIP_NO_CACHE_DIR=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        fonts-noto-core \
        fonts-noto-cjk \
        fontconfig \
        libgl1 \
        libglib2.0-0 && \
    fc-cache -fv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install -e '/app/third_party/MinerU[vlm,vllm]'

EXPOSE 30000

ENTRYPOINT ["mineru-openai-server"]
CMD ["--host", "0.0.0.0", "--port", "30000"]
